require:
- rubocop-rails
- rubocop-rspec

AllCops:
  NewCops: enable
  Exclude: 
    - bin/*
    - db/schema.rb
    - db/migrate/*
    - config/environments/*
    - config/routes.rb
    - Gemfile
    - spec/factories/*

Style/Documentation:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Rails/I18nLocaleTexts: 
  Enabled: false

Metrics/AbcSize: 
  Enabled: false

Metrics/MethodLength:
  Enabled: false
    